src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $preparationTime;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $CookingTime;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $peopleNumber;

    /**
     * @ORM\OneToMany(targetEntity=RecipeIngredient::class, mappedBy="recipe")
     * @var RecipeIngredient[]|ArrayCollection
     */
    private $ingredients;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $difficulty;

    /**
     * @ORM\Column(type="text")
     * @var string
     */
    private $resume;

    /**
     * @ORM\OneToMany(targetEntity=RecipeStep::class, mappedBy="recipe")
     * @var RecipeStep[]|ArrayCollection
     */
    private $steps;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->steps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparationTime;
    }

    public function setPreparationTime(int $preparationTime): self
    {
        $this->preparationTime = $preparationTime;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->CookingTime;
    }

    public function setCookingTime(int $CookingTime): self
    {
        $this->CookingTime = $CookingTime;

        return $this;
    }

    public function getPeopleNumber(): ?int
    {
        return $this->peopleNumber;
    }

    public function setPeopleNumber(int $peopleNumber): self
    {
        $this->peopleNumber = $peopleNumber;

        return $this;
    }

    /**
     * @return Collection|RecipeIngredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(RecipeIngredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->setRecipe($this);
        }

        return $this;
    }

    public function removeIngredient(RecipeIngredient $ingredient): self
    {
        if ($this->ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecipe() === $this) {
                $ingredient->setRecipe(null);
            }
        }

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * @return Collection|RecipeStep[]
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(RecipeStep $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps[] = $step;
            $step->setRecipe($this);
        }

        return $this;
    }

    public function removeStep(RecipeStep $step): self
    {
        if ($this->steps->removeElement($step)) {
            // set the owning side to null (unless already changed)
            if ($step->getRecipe() === $this) {
                $step->setRecipe(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 *
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/recette/{id}", name="recipe_detail")
     */
    public function RecipeDetail(Recipe $recipe): Response
    {
        return $this->render('recipes/detail.html.twig', [
      'recipe' => $recipe,
    ]);
    }
}

templates/recipes/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Recette - {{ recipe.title }}
{% endblock %}

{% block body %}
<div class="grid-x grid-padding-x">
  <div class="large-12 cell">
    <h1>Recette - {{ recipe.title }}</h1>
  </div>
</div>

  <div class="grid-x grid-padding-x">
    <div class="row cell medium-12 large-9">
      <img class="thumbnail" src="https://placehold.it/800x400">
    </div>
    <div class="row cell medium-12 large-3 reipe-infos">
      <div class="recipe-info">
        <div class="recipe-info__title">Temps de préparation</div>
        <div class="recipe-info__value">{{ recipe.preparationTime }}</div>
      </div>
      <div class="recipe-info">
        <div class="recipe-info__title">Temps de cuisson</div>
        <div class="recipe-info__value">{{ recipe.cookingTime }}</div>
      </div>
      <div class="recipe-info">
        <div class="recipe-info__title">Nombre de personnes</div>
        <div class="recipe-info__value">{{ recipe.peopleNumber }}</div>
      </div>
      <div class="recipe-info">
        <div class="recipe-info__title">Difficulté</div>
        <div class="recipe-info__value">{{ recipe.difficulty }}</div>
      </div>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="large-12 cell">
      <h2>Résumé</h2>
      {{recipe.resume }}
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="medium-12 large-4 row cell">
      <h2>Ingrédients</h2>
      <ul>
        {% for ingredient in recipe.ingredients %}
          <li>{{ ingredient.quantity }} {{ ingredient.unity}} de {{ ingredient.name }} </li>
        {% else %}
        <li>Aucun ingédient</li>
        {% endfor %}
      </ul>
    </div>
    <div class="medium-12 large-8 row cell">
      <h2>Etapes</h2>
      <ol>
        {% for step in recipe.steps %}
          <li>{{ step.body }}</li>
        {% endfor %}
      </ol>
    </div>
  </div>
{% endblock %}